# Internal role variables specific to: Debian (os_family or distribution)
#
# Only values specific to the platform and its functionality should be included
# here. Variables in this file override those defined in vars/main.yml.
#
# Each variable should have a concise comment above it, describing its purpose
# and how it fits into the role's functionality.

---

__run_sshd_config_file_mode: "u=rw,g=r,o=r" # 0644

__run_sshd_config_dropin_dir_mode: "u=rwx,g=rx,o=rx" # 0755

__run_sshd_config_dropin_file_mode: "{{ __run_sshd_config_file_mode }}"

__run_sshd_hostkey_files_mode: "u=rw,g=,o=" # 0600

# Check vars/main.yml for hints on determining the privilege separation dir path
__run_sshd_privseparation_dir_path: "/run/sshd"
__run_sshd_privseparation_dir_mode: "u=rwx,g=rx,o=rx" # 0755

__run_sshd_sshd_servicename: "ssh.service"
