# Tasks for the Molecule converge stage: Execute the collection role "run"
# against all driver-created instances.

- name: "Molecule | Converge | Include the foundata.sshd.run role"
  ansible.builtin.include_role:
    name: "foundata.sshd.run"
  vars:
    run_sshd_state: "present"
    run_sshd_config_dropin_file_name: "00-custom-dropin.conf"
    run_sshd_sshd_settings:
      PrintLastLog: true # should get overwritten on SUSE due to incompatibility
