# Tasks for the Molecule prepare stage: Add resources needed for later steps
# (e.g. verify) on all driver-created instances.

- name: "Molecule | Prepare | Install packages needed for pip"
  ansible.builtin.package:
    name:
      - "python3-packaging"
      - "python3-pip"
    state: "present"


- name: "Molecule | Prepare | Install ssh-audit"
  ansible.builtin.pip:
    name:
      - "ssh-audit"
    state: "present"
    break_system_packages: true
